apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: my-cluster
rendezvousIP: 192.168.1.10
hosts:
  - hostname: master-0
    role: master
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: bond0
        type: bond
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.1.10
              prefix-length: 24
          dhcp: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          options:
            miimon: "100"
            lacp_rate: "fast"
          port:
            - ens3
            - ens4
      - name: ens3
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: ens4
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.10
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: "100"
              lacp_rate: "fast"
            port:
              - ens3
              - ens4
        - name: ens3
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens4
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: bond0

  - hostname: worker-0
    role: worker
    rootDeviceHints:
      deviceName: /dev/sda
    interfaces:
      - name: bond0
        type: bond
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.1.20
              prefix-length: 24
          dhcp: false
        ipv6:
          enabled: false
        link-aggregation:
          mode: 802.3ad
          options:
            miimon: "100"
            lacp_rate: "fast"
          port:
            - ens3
            - ens4
      - name: ens3
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: ens4
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
    networkConfig:
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            enabled: true
            address:
              - ip: 192.168.1.20
                prefix-length: 24
            dhcp: false
          ipv6:
            enabled: false
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: "100"
              lacp_rate: "fast"
            port:
              - ens3
              - ens4
        - name: ens3
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
        - name: ens4
          type: ethernet
          state: up
          ipv4:
            enabled: false
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.1.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.1.1
            next-hop-interface: bond0
